### ISSUE TITLE
IDE download link goes nowhere

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/welcome-to-learn-4#3]
The IDE download link goes nowhere, which is creating lots of confusion for students:

`<a class="js--download-ide" href="#">Click here to create a Learn account and Download the Learn IDE</a>`

This link should point to: https://learn.co/ide

**Comment by kvignali** [comment]
@ivalentine this actually isn't the case - this link works if your user hasn't downloaded the IDE previously. Since it's connected to a modal that pops up for account creation, the link is different than /ide.
