### ISSUE TITLE
MoveFile failed; code 3

### ISSUE THREAD

**Issue by HavocBlast** [learn-co-curriculum/welcome-to-learn-4#4]
I was trying to install the IDE on my windows 10 pro computer and got this error. I tried running installer in both admin and compatibility with no luck. I tried to reboot my system and install but that failed as well.

My next action was to download the IDE via learn.co/ide and that failed as well.

I know that the IDE is based on the Atom editor so I tried to install the base editor from Atom's site and that worked as plan so I am wondering what went wrong here.

I am currently using the IDE on my mac which installed just fine until a fix is found for the Windows version. 
![capture](https://cloud.githubusercontent.com/assets/6200605/18031317/33b84ca6-6ca9-11e6-9e62-cf608d77df76.PNG)

**Comment by AnnJohn** [comment]
hi @BananaClipStudio thanks for raising this. We use this space for issues specifically related to the content in curriculum. For this and other product issues, could you file a bug report? If you click on your profile pic in Learn, you'll see a menu with an option to Report a Bug. Thanks!
